django_typeBiet/django_api1/src/blog/api/urls.py
from django.urls import path

from blog.api.views import (
    api_detail_blog_view,
    api_update_blog_view,
    api_create_blog_view,
    api_delete_blog_view,
)


app_name = 'blog'

urlpatterns = [
    path('<slug>/', api_detail_blog_view, name="detail"),
    path('<slug>/update', api_detail_blog_view, name="update"),
    path('create', api_detail_blog_view, name="create"),
    path('<slug>/delete', api_detail_blog_view, name="delete"),        
]

django_typeBiet/django_api1/src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,
)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
]

django_typeBiet/django_api1/src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    #REST FRAMEWORK URL
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    #path('api/account/', include('account.api.urls', 'account_api')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
    name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), 
    name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), 
    name='password_reset_complete'),
]
"""
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)"""

django_typeBiet/django_api1/src/blog/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


def upload_location(instance, filename, **kwargs):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id), title=str(instance.title), filename=filename
		) 
	return file_path


class BlogPost(models.Model):
	title 				= models.CharField(max_length=50, null=False, blank=False)
	body 				= models.TextField(max_length=5000, null=False, blank=False)
	image 				= models.ImageField(upload_to=upload_location, null=False, blank=False)
	date_published 		= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated 		= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 				= models.SlugField(blank=True, unique=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete(False)

def pre_save_blog_post_receiever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiever, sender=BlogPost)

django_typeBiet/django_api1/src/blog/forms.py
from django import forms

from blog.models import BlogPost


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']



class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post

django_typeBiet/django_api1/src/blog/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view

from account.models import Account
from blog.models import BlogPost
from blog.api.serializers import BlogPostSerializer

@api_view(['GET',])
def api_detail_blog_view(request, slug):
    
    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist: 
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        serializers = BlogPostSerializer(blog_post)
        return Response(serializer.data)

@api_view(['PUT',])
def api_update_blog_view(request, slug):
    
    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist: 
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "POST":
        serializers = BlogPostSerializer(blog_post, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            data["success"] = "update succesful"
            return Response(data=data)
        return Response(serializer.errors, status=status.HTTP_404_BAD_REQUEST)

@api_view(['POST',])
def api_create_blog_view(request, slug):

    account = Account.objects.get(pk=1)

    blog_post = BlogPost(author=account)
    if request.method == "POST":
        serializer = BlogPostSerializer(blog_post, data=request.data)
        data = {}
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE',])
def api_delete_blog_view(request, slug):
    
    try:
        blog_post = BlogPost.objects.get(slug=slug)
    except BlogPost.DoesNotExist: 
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "DELETE":
        operation = blog_post.delete()
        data = {}
        if operation:
            data["success dilet"] = "delete success"
        else:
            data['failure delete'] = "delete fail"
        return Response(data=data)

django_typeBiet/django_api1/src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse

from blog.models import BlogPost
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account


def create_blog_view(request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()

	context['form'] = form

	return render(request, "blog/create_blog.html", context)


def detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)



def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse("You are not the author of that post.")

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "Updated"
			blog_post = obj

	form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
			}
		)

	context['form'] = form
	return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))

django_typeBiet/django_api1/src/blog/templates/blog/snippets/blog_post_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if blog_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in blog_posts.paginator.page_range %}
		{% if blog_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if blog_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ blog_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

django_typeBiet/django_api1/src/blog/templates/blog/snippets/blog_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;

	}
</style>

{% if blog_post %}
<div class="container">
	<div class="row">

		
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'blog:detail' post.slug %}">
				<img class="card-img-top" src="{{blog_post.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'blog:detail' post.slug %}">
					<h2 class="card-title">{{blog_post.title}}</h2>
				</a>
				<p class="card-text">{{blog_post.body|safe|truncatechars:250}}</p>
				{% if blog_post.author == request.user %}
					<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
				{% endif %}
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
			</div>
		</div>
		
	</div>
</div>

{% else %}

<div class="container"> 
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">
					No results
				</h2>
				<p class="card-text">There were no results matching your search: "{{query}}".</p>
			</div>
		</div>
	</div>
</div>
{% endif %}